version: '3.8'

services:
  backend:
    build: ./backend
    container_name: laravel-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - laravel-net
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: serverlist
      DB_USERNAME: root
      DB_PASSWORD: root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - laravel-net
    environment:
      VITE_API_URL: http://localhost:8000/api
    command: npm run dev -- --host 0.0.0.0

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: serverlist
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root

volumes:
  db_data:

networks:
  laravel-net:
    driver: bridge